%% Shared STP constants. Keep protocol numbers, persisted schema versions,
%% application environment keys, and table names here instead of scattering
%% literals across modules.

-ifndef(TELCO_STP_HRL).
-define(TELCO_STP_HRL, true).

-define(STP_APP, telco_stp).

%% ETS tables.
-define(STP_METRICS_TABLE, telco_stp_metrics_table).

%% Common integer limits.
-define(STP_UINT8_MAX, 16#ff).
-define(STP_UINT16_MAX, 16#ffff).
-define(STP_UINT32_MAX, 16#ffffffff).
-define(STP_POINT_CODE_MASK_24, 16#ffffff).
-define(STP_ITU_POINT_CODE_MAX, 16#3fff).
-define(STP_MAX_MILLISECONDS, 3600000).
-define(STP_MAX_SHORT_BYTES, 65535).
-define(STP_MICROSECONDS_PER_MILLISECOND, 1000).
-define(STP_MICROSECONDS_PER_SECOND, 1000000).
-define(STP_PERCENT_SCALE, 100).

%% M3UA / SCTP.
-define(STP_M3UA_VERSION, 1).
-define(STP_M3UA_PPID, 3).
-define(STP_M3UA_NETWORK_PPID, 16#03000000).
-define(STP_M3UA_PORT, 2905).
-define(STP_M3UA_PARAM_INFO_STRING, 16#0004).
-define(STP_M3UA_PARAM_ROUTING_CONTEXT, 16#0006).
-define(STP_M3UA_PARAM_DIAGNOSTIC_INFORMATION, 16#0007).
-define(STP_M3UA_PARAM_HEARTBEAT_DATA, 16#0009).
-define(STP_M3UA_PARAM_TRAFFIC_MODE_TYPE, 16#000b).
-define(STP_M3UA_PARAM_ERROR_CODE, 16#000c).
-define(STP_M3UA_PARAM_STATUS, 16#000d).
-define(STP_M3UA_PARAM_ASP_IDENTIFIER, 16#0011).
-define(STP_M3UA_PARAM_AFFECTED_POINT_CODE, 16#0012).
-define(STP_M3UA_PARAM_CORRELATION_ID, 16#0013).
-define(STP_M3UA_PARAM_NETWORK_APPEARANCE, 16#0200).
-define(STP_M3UA_PARAM_USER_CAUSE, 16#0204).
-define(STP_M3UA_PARAM_CONGESTION_INDICATIONS, 16#0205).
-define(STP_M3UA_PARAM_CONCERNED_DESTINATION, 16#0206).
-define(STP_M3UA_PARAM_ROUTING_KEY, 16#0207).
-define(STP_M3UA_PARAM_REGISTRATION_RESULT, 16#0208).
-define(STP_M3UA_PARAM_DEREGISTRATION_RESULT, 16#0209).
-define(STP_M3UA_PARAM_LOCAL_RK_IDENTIFIER, 16#020a).
-define(STP_M3UA_PARAM_DESTINATION_POINT_CODE, 16#020b).
-define(STP_M3UA_PARAM_SERVICE_INDICATORS, 16#020c).
-define(STP_M3UA_PARAM_ORIGINATING_POINT_CODE, 16#020e).
-define(STP_M3UA_PARAM_PROTOCOL_DATA, 16#0210).
-define(STP_M3UA_PARAM_REGISTRATION_STATUS, 16#0212).
-define(STP_M3UA_PARAM_DEREGISTRATION_STATUS, 16#0213).
-define(STP_M3UA_ERROR_INVALID_VERSION, 16#01).
-define(STP_M3UA_ERROR_UNSUPPORTED_MESSAGE_CLASS, 16#03).
-define(STP_M3UA_ERROR_UNSUPPORTED_MESSAGE_TYPE, 16#04).
-define(STP_M3UA_ERROR_UNSUPPORTED_TRAFFIC_MODE, 16#05).
-define(STP_M3UA_ERROR_UNEXPECTED_MESSAGE, 16#06).
-define(STP_M3UA_ERROR_PROTOCOL_ERROR, 16#07).
-define(STP_M3UA_ERROR_INVALID_STREAM_IDENTIFIER, 16#09).
-define(STP_M3UA_ERROR_MANAGEMENT_BLOCKING, 16#0d).
-define(STP_M3UA_ERROR_ASP_IDENTIFIER_REQUIRED, 16#0e).
-define(STP_M3UA_ERROR_INVALID_ASP_IDENTIFIER, 16#0f).
-define(STP_M3UA_ERROR_INVALID_PARAMETER_VALUE, 16#11).
-define(STP_M3UA_ERROR_PARAMETER_FIELD_ERROR, 16#12).
-define(STP_M3UA_ERROR_UNEXPECTED_PARAMETER, 16#13).
-define(STP_M3UA_ERROR_DESTINATION_STATUS_UNKNOWN, 16#14).
-define(STP_M3UA_ERROR_INVALID_NETWORK_APPEARANCE, 16#15).
-define(STP_M3UA_ERROR_MISSING_PARAMETER, 16#16).
-define(STP_M3UA_ERROR_INVALID_ROUTING_CONTEXT, 16#19).
-define(STP_M3UA_ERROR_NO_CONFIGURED_AS, 16#1a).

%% M2PA / SCTP.
-define(STP_M2PA_VERSION, 1).
-define(STP_M2PA_CLASS, 11).
-define(STP_M2PA_PPID, 5).
-define(STP_M2PA_NETWORK_PPID, 16#05000000).
-define(STP_M2PA_PORT, 3565).
-define(STP_M2PA_MAX_SEQUENCE, 16#ffffff).

%% SCCP message types.
-define(STP_SCCP_UDT, 16#09).
-define(STP_SCCP_UDTS, 16#0a).
-define(STP_SCCP_XUDT, 16#11).
-define(STP_SCCP_XUDTS, 16#12).
-define(STP_SCCP_LUDT, 16#13).
-define(STP_SCCP_LUDTS, 16#14).
-define(STP_SCCP_OPTION_SEGMENTATION, 16#10).
-define(STP_SCCP_OPTION_IMPORTANCE, 16#12).

%% MTP3 Signalling Network Management Message groups, Q.704 H0.
-define(STP_SNMM_H0_CHM, 1).
-define(STP_SNMM_H0_ECM, 2).
-define(STP_SNMM_H0_FCM, 3).
-define(STP_SNMM_H0_TFM, 4).
-define(STP_SNMM_H0_RSM, 5).
-define(STP_SNMM_H0_MIM, 6).
-define(STP_SNMM_H0_TRM, 7).
-define(STP_SNMM_H0_DLM, 8).
-define(STP_SNMM_H0_UFC, 10).
-define(STP_SNMM_H0_UPU, 11).

%% MTP3 service indicator for signalling network management.
-define(STP_MTP3_SI_SNMM, 0).
-define(STP_MTP3_ITU_OPC_SHIFT, 14).
-define(STP_MTP3_ITU_SLS_SHIFT, 28).
-define(STP_MTP3_SLS_MASK, 16#0f).

%% Configuration persistence and HA schemas.
-define(STP_CONFIG_MAGIC, <<"TSTPCFG", 1>>).
-define(STP_CONFIG_SCHEMA_VERSION, 1).
-define(STP_HA_SCHEMA_VERSION, 1).

%% Audit.
-define(STP_ZERO_HASH, <<0:256>>).
-define(STP_AUDIT_MAX_FRAME_BYTES, 16777216).
-define(STP_DEFAULT_AUDIT_HISTORY_LIMIT, 10000).
-define(STP_MAX_AUDIT_HISTORY_LIMIT, 1000000).

%% GTT.
-define(STP_GTT_DEFAULT_MAX_CHAIN_DEPTH, 8).
-define(STP_GTT_MAX_CHAIN_DEPTH, 64).

%% PCAPNG trace.
-define(STP_PCAPNG_SHB_TYPE, 16#0a0d0d0a).
-define(STP_PCAPNG_IDB_TYPE, 1).
-define(STP_PCAPNG_EPB_TYPE, 6).
-define(STP_PCAPNG_DLT_USER0, 147).
-define(STP_PCAPNG_BYTE_ORDER_MAGIC, 16#1a2b3c4d).
-define(STP_PCAPNG_UNSPECIFIED_SECTION_LENGTH, 16#ffffffffffffffff).
-define(STP_PCAPNG_DEFAULT_SNAPLEN, 16#00040000).
-define(STP_TRACE_DIRECTION_RX, 0).
-define(STP_TRACE_DIRECTION_TX, 1).

%% Runtime defaults.
-define(STP_DEFAULT_CALL_TIMEOUT_MS, 5000).
-define(STP_DEFAULT_LONG_CALL_TIMEOUT_MS, 10000).
-define(STP_DEFAULT_OPERATION_TIMEOUT_MS, 30000).
-define(STP_DEFAULT_PROMOTION_TIMEOUT_MS, 60000).
-define(STP_DEFAULT_SUPERVISOR_SHUTDOWN_MS, 5000).
-define(STP_DEFAULT_RECONNECT_MS, 1000).
-define(STP_LINK_RESTART_RETRY_MS, 500).
-define(STP_DEFAULT_CONNECT_TIMEOUT_MS, 5000).
-define(STP_DEFAULT_HEARTBEAT_TIMEOUT_MS, 10000).
-define(STP_DEFAULT_ALARM_LIMIT, 1000).
-define(STP_DEFAULT_OVERLOAD_HIGH_WATERMARK, 10000).
-define(STP_DEFAULT_OVERLOAD_LOW_WATERMARK, 5000).
-define(STP_DEFAULT_RKM_RC_START, 10000).
-define(STP_DEFAULT_RKM_MAX_REGISTRATIONS, 4096).
-define(STP_MAX_RKM_REGISTRATIONS, 1000000).
-define(STP_DEFAULT_M2PA_PROVING_MS, 500).
-define(STP_DEFAULT_M2PA_ALIGNMENT_TIMEOUT_MS, 60000).
-define(STP_DEFAULT_M2PA_T7_MS, 10000).
-define(STP_DEFAULT_M2PA_MAX_UNACKED, 10000).
-define(STP_DEFAULT_HA_INTERVAL_MS, 1000).
-define(STP_DEFAULT_HA_MAX_STALENESS_MS, 10000).
-define(STP_DEFAULT_HA_MAX_CLOCK_SKEW_MS, 5000).
-define(STP_DEFAULT_HA_REPLICATION_TIMEOUT_MS, 2000).
-define(STP_MIN_HA_INTERVAL_MS, 100).
-define(STP_MIN_HA_REPLICATION_TIMEOUT_MS, 100).
-define(STP_MAX_HA_CLOCK_SKEW_MS, 60000).
-define(STP_MAX_HA_REPLICATION_TIMEOUT_MS, 60000).
-define(STP_DEFAULT_TRACE_MAX_PACKETS, 10000).
-define(STP_DEFAULT_TRACE_MAX_BYTES, 67108864).
-define(STP_DEFAULT_TRACE_HEADER_BYTES, 128).
-define(STP_DEFAULT_LISTENER_BACKLOG, 128).
-define(STP_DEFAULT_REASSEMBLY_MAX_CONTEXTS, 10000).
-define(STP_DEFAULT_REASSEMBLY_CONTEXT_BYTES, 65536).
-define(STP_DEFAULT_REASSEMBLY_TOTAL_BYTES, 67108864).
-define(STP_DEFAULT_REASSEMBLY_TIMEOUT_MS, 10000).
-define(STP_MAX_LOAD_CONCURRENCY, 1024).

%% Application environment keys.
-define(STP_ENV_AUDIT_HISTORY_LIMIT, audit_history_limit).
-define(STP_ENV_AUDIT_LOG_PATH, audit_log_path).
-define(STP_ENV_GTT_MAX_CHAIN_DEPTH, gtt_max_chain_depth).
-define(STP_ENV_HA, ha).
-define(STP_ENV_RKM_POLICY, rkm_policy).
-define(STP_ENV_TRACE, trace).
-define(STP_ENV_ALARM_HISTORY_LIMIT, alarm_history_limit).
-define(STP_ENV_ACTIVE_ALARM_LIMIT, active_alarm_limit).
-define(STP_ENV_LINKS, links).
-define(STP_ENV_ROUTES, routes).
-define(STP_ENV_GTT_RULES, gtt_rules).
-define(STP_ENV_LISTENERS, listeners).
-define(STP_ENV_FAULT_PROFILE, fault_profile).
-define(STP_ENV_OVERLOAD_LIMITS, overload_limits).
-define(STP_ENV_SCCP_REASSEMBLY_LIMITS, sccp_reassembly_limits).
-define(STP_ENV_MANAGEMENT_CREDENTIALS, management_credentials).

-endif.
